name: create-global
on: 
  issues:
    types: [opened]
jobs:
  create-global-variable:
    environment: globals-repo-secret
    name: Job for creating and storing the global
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Python
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create the global variable
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          HOME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GLOBALS_REPO_TOKEN: ${{ secrets.TOKEN }}
        run: | 
          pip3 install PyGithub
          python3 create_global_from_issue.py
